### PR TITLE
refactor zaCalendar 

### PR DESCRIPTION
**Pull request by li2568261**
refactor zaCalendar

### CODE REVIEW

**Comment by li2568261** [comment]
fix the style, test rewrite

**Comment by li2568261** [comment]
fix(calendar): string date normalize
fix(calendar): use the zarm scss variables
fix(calendar): Optimize the watch

**Comment by li2568261** [comment]
add disabledDate filter test

**Comment by li2568261** [comment]
recover jest.conf.js remove testMath

**Comment by chuanshuoye** [comment]
OK

**Pull request merged**
